all: circularLeftShift classification fibonacciSequence optimization

circularLeftShift:	circularLeftShift.cpp
	g++ circularLeftShift.cpp -o circularLeftShift

classification:	classification.cpp
	g++ classification.cpp -o classification

fibonacciSequence:	fibonacciSequence.cpp
	g++ fibonacciSequence.cpp -o fibonacciSequence

optimization:	optimization.cpp
	g++ optimization.cpp -o optimization

clean:
	rm circularLeftShift classification fibonacciSequence optimization
