all: bmi location line lod

bmi:	bodyMassIndex.cpp
	g++ bodyMassIndex.cpp -o bodyMassIndex

location:	determineLocation.cpp
	g++ determineLocation.cpp -o determineLocation

line:	equationStraightLine.cpp
	g++ equationStraightLine.cpp -o equationStraightLine

lod:	letterOrDigit.cpp
	g++ letterOrDigit.cpp -o letterOrDigit

clean:
	rm bodyMassIndex determineLocation equationStraightLine letterOrDigit
