all: expenseManager pointerExercise

expenseManager:	expenseManager.cpp
	g++ expenseManager.cpp -o expenseManager

pointerExercise:	pointerExercise.cpp
	g++ pointerExercise.cpp -o pointerExercise

clean:
	rm expenseManager pointerExercise
