all: carClass dealerPlayerCardShuffler

carClass:	carClass.cpp
	g++ carClass.cpp -o carClass

dealerPlayerCardShuffler: dealerPlayerCardShuffler.cpp
	g++ dealerPlayerCardShuffler.cpp -o dealerPlayerCardShuffler

clean:
	rm carClass dealerPlayerCardShuffler
