all:	areaCalculator	BMIDatabase	examScore

areaCalculator:	areaCalculator.cpp
	g++ areaCalculator.cpp -o areaCalculator

BMIDatabase:	BMIDatabase.cpp
	g++ BMIDatabase.cpp -o BMIDatabase

examScore:	examScore.cpp
	g++ examScore.cpp -o examScore

clean:
	rm areaCalculator BMIDatabase examScore
