all: binarySearch cardShuffler

binarySearch: binarySearch.cpp
	g++ binarySearch.cpp -o binarySearch

cardShuffler: cardShuffler.cpp
	g++ cardShuffler.cpp -o cardShuffler

clean:
	rm binarySearch cardShuffler
