all: analysisMovieData widgetFactory

analysisMovieData:	analysisMovieData.cpp
	g++ analysisMovieData.cpp -o analysisMovieData

widgetFactory:	widgetFactory.cpp
	g++ widgetFactory.cpp -o widgetFactory

clean:
	rm analysisMovieData widgetFactory
